### ISSUE TITLE
自动搜索GPU搜不到，手动指定又报错

### ISSUE THREAD

**Issue by tju-sun-lab** [yn-sun/ea-cnn#7]
2022-04-13 19:53:09,031 INFO    : *************************
2022-04-13 19:53:09,031 INFO    : Initialize from existing population data
2022-04-13 19:53:09,031 INFO    : Initialize from 0-th generation
2022-04-13 19:53:09,044 INFO    : EVOLVE[0-gen]-Begin to evaluate the fitness
2022-04-13 19:53:09,044 INFO    : Begin to generate python files
2022-04-13 19:53:09,055 INFO    : Finish the generation of python files
2022-04-13 19:53:09,055 INFO    : Query fitness from cache
2022-04-13 19:53:09,055 INFO    : Total hit 0 individuals for fitness
2022-04-13 19:53:09,055 INFO    : Begin to train indi0000
2022-04-13 19:53:09,597 INFO    : Begin to train indi0001
2022-04-13 19:53:09,604 INFO    : Begin to train indi0002
2022-04-13 19:53:09,612 INFO    : Begin to train indi0003
2022-04-13 19:53:09,619 INFO    : Begin to train indi0004
2022-04-13 19:53:09,626 INFO    : Begin to train indi0005
2022-04-13 19:53:09,634 INFO    : Begin to train indi0006
2022-04-13 19:53:09,641 INFO    : Begin to train indi0007
2022-04-13 19:53:09,649 INFO    : Begin to train indi0008
2022-04-13 19:53:09,662 INFO    : Begin to train indi0009
2022-04-13 19:53:09,675 INFO    : Begin to train indi0010
2022-04-13 19:53:09,688 INFO    : Begin to train indi0011
2022-04-13 19:53:09,701 INFO    : Begin to train indi0012
2022-04-13 19:53:09,715 INFO    : Begin to train indi0013
2022-04-13 19:53:09,728 INFO    : Begin to train indi0014
2022-04-13 19:53:09,742 INFO    : Begin to train indi0015
2022-04-13 19:53:09,756 INFO    : Begin to train indi0016
2022-04-13 19:53:09,770 INFO    : Begin to train indi0017
2022-04-13 19:53:09,792 INFO    : Begin to train indi0018
2022-04-13 19:53:09,822 INFO    : Begin to train indi0019
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Exception occurs, file:indi0019, pid:30939...CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Process Process-20:
Exception occurs, file:indi0003, pid:30923...CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Process Process-4:
Traceback (most recent call last):
  File "/work/sunbiao/ea-cnn-master/scripts/indi0003.py", line 227, in do_work
    m = TrainModel()
  File "/work/sunbiao/ea-cnn-master/scripts/indi0003.py", line 145, in __init__
    net = net.cuda()
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 637, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 552, in _apply
    param_applied = fn(param)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 637, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/work/sunbiao/ea-cnn-master/scripts/indi0003.py", line 234, in do_work
    m.log_record('Exception occur:%s'%(str(e)))
UnboundLocalError: local variable 'm' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/work/sunbiao/ea-cnn-master/scripts/indi0003.py", line 236, in do_work
    m.log_record('Finished-Acc:%.3f'%best_acc)
UnboundLocalError: local variable 'm' referenced before assignment
Exception occurs, file:indi0009, pid:30929...CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Process Process-10:
Traceback (most recent call last):
  File "/work/sunbiao/ea-cnn-master/scripts/indi0009.py", line 225, in do_work
    m = TrainModel()
  File "/work/sunbiao/ea-cnn-master/scripts/indi0009.py", line 143, in __init__
    net = net.cuda()
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 637, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 552, in _apply
    param_applied = fn(param)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 637, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/work/sunbiao/ea-cnn-master/scripts/indi0009.py", line 232, in do_work
    m.log_record('Exception occur:%s'%(str(e)))
UnboundLocalError: local variable 'm' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/work/sunbiao/ea-cnn-master/scripts/indi0009.py", line 234, in do_work
    m.log_record('Finished-Acc:%.3f'%best_acc)
UnboundLocalError: local variable 'm' referenced before assignment
Exception occurs, file:indi0014, pid:30934...CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Process Process-15:
Traceback (most recent call last):
  File "/work/sunbiao/ea-cnn-master/scripts/indi0014.py", line 223, in do_work
    m = TrainModel()
  File "/work/sunbiao/ea-cnn-master/scripts/indi0014.py", line 141, in __init__
    net = net.cuda()
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 637, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 552, in _apply
    param_applied = fn(param)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 637, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/work/sunbiao/ea-cnn-master/scripts/indi0014.py", line 230, in do_work
    m.log_record('Exception occur:%s'%(str(e)))
UnboundLocalError: local variable 'm' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/work/sunbiao/ea-cnn-master/scripts/indi0014.py", line 232, in do_work
    m.log_record('Finished-Acc:%.3f'%best_acc)
UnboundLocalError: local variable 'm' referenced before assignment
Exception occurs, file:indi0017, pid:30937...CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Process Process-18:
Traceback (most recent call last):
  File "/work/sunbiao/ea-cnn-master/scripts/indi0017.py", line 225, in do_work
    m = TrainModel()
  File "/work/sunbiao/ea-cnn-master/scripts/indi0017.py", line 143, in __init__
    net = net.cuda()
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 637, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 552, in _apply
    param_applied = fn(param)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 637, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/work/sunbiao/ea-cnn-master/scripts/indi0017.py", line 232, in do_work
    m.log_record('Exception occur:%s'%(str(e)))
UnboundLocalError: local variable 'm' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/work/sunbiao/ea-cnn-master/scripts/indi0017.py", line 234, in do_work
    m.log_record('Finished-Acc:%.3f'%best_acc)
UnboundLocalError: local variable 'm' referenced before assignment
Exception occurs, file:indi0012, pid:30932...CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Process Process-13:
Traceback (most recent call last):
  File "/work/sunbiao/ea-cnn-master/scripts/indi0012.py", line 225, in do_work
    m = TrainModel()
  File "/work/sunbiao/ea-cnn-master/scripts/indi0012.py", line 143, in __init__
    net = net.cuda()
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 637, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 552, in _apply
    param_applied = fn(param)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 637, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/work/sunbiao/ea-cnn-master/scripts/indi0012.py", line 232, in do_work
    m.log_record('Exception occur:%s'%(str(e)))
UnboundLocalError: local variable 'm' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/work/sunbiao/ea-cnn-master/scripts/indi0012.py", line 234, in do_work
    m.log_record('Finished-Acc:%.3f'%best_acc)
UnboundLocalError: local variable 'm' referenced before assignment
Exception occurs, file:indi0007, pid:30927...CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Process Process-8:
Exception occurs, file:indi0016, pid:30936...CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Process Process-17:
Traceback (most recent call last):
  File "/work/sunbiao/ea-cnn-master/scripts/indi0007.py", line 227, in do_work
    m = TrainModel()
  File "/work/sunbiao/ea-cnn-master/scripts/indi0007.py", line 145, in __init__
    net = net.cuda()
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 637, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 552, in _apply
    param_applied = fn(param)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 637, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/work/sunbiao/ea-cnn-master/scripts/indi0007.py", line 234, in do_work
    m.log_record('Exception occur:%s'%(str(e)))
UnboundLocalError: local variable 'm' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/work/sunbiao/ea-cnn-master/scripts/indi0007.py", line 236, in do_work
    m.log_record('Finished-Acc:%.3f'%best_acc)
UnboundLocalError: local variable 'm' referenced before assignment
  File "/work/sunbiao/ea-cnn-master/scripts/indi0016.py", line 225, in do_work
    m = TrainModel()
  File "/work/sunbiao/ea-cnn-master/scripts/indi0016.py", line 143, in __init__
    net = net.cuda()
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 637, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 552, in _apply
    param_applied = fn(param)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 637, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/work/sunbiao/ea-cnn-master/scripts/indi0016.py", line 232, in do_work
    m.log_record('Exception occur:%s'%(str(e)))
UnboundLocalError: local variable 'm' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/work/sunbiao/ea-cnn-master/scripts/indi0016.py", line 234, in do_work
    m.log_record('Finished-Acc:%.3f'%best_acc)
UnboundLocalError: local variable 'm' referenced before assignment
Exception occurs, file:indi0015, pid:30935...CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Process Process-16:
Traceback (most recent call last):
  File "/work/sunbiao/ea-cnn-master/scripts/indi0015.py", line 225, in do_work
    m = TrainModel()
  File "/work/sunbiao/ea-cnn-master/scripts/indi0015.py", line 143, in __init__
    net = net.cuda()
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 637, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 552, in _apply
    param_applied = fn(param)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 637, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/work/sunbiao/ea-cnn-master/scripts/indi0015.py", line 232, in do_work
    m.log_record('Exception occur:%s'%(str(e)))
UnboundLocalError: local variable 'm' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/work/sunbiao/ea-cnn-master/scripts/indi0015.py", line 234, in do_work
    m.log_record('Finished-Acc:%.3f'%best_acc)
UnboundLocalError: local variable 'm' referenced before assignment
Exception occurs, file:indi0013, pid:30933...CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Process Process-14:
Traceback (most recent call last):
  File "/work/sunbiao/ea-cnn-master/scripts/indi0013.py", line 227, in do_work
    m = TrainModel()
  File "/work/sunbiao/ea-cnn-master/scripts/indi0013.py", line 145, in __init__
    net = net.cuda()
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 637, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 552, in _apply
    param_applied = fn(param)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 637, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/work/sunbiao/ea-cnn-master/scripts/indi0013.py", line 234, in do_work
    m.log_record('Exception occur:%s'%(str(e)))
UnboundLocalError: local variable 'm' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/work/sunbiao/ea-cnn-master/scripts/indi0013.py", line 236, in do_work
    m.log_record('Finished-Acc:%.3f'%best_acc)
UnboundLocalError: local variable 'm' referenced before assignment
Exception occurs, file:indi0018, pid:30938...CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Exception occurs, file:indi0006, pid:30926...CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.Process Process-19:

Process Process-7:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/work/sunbiao/ea-cnn-master/scripts/indi0018.py", line 223, in do_work
    m = TrainModel()
  File "/work/sunbiao/ea-cnn-master/scripts/indi0006.py", line 225, in do_work
    m = TrainModel()
  File "/work/sunbiao/ea-cnn-master/scripts/indi0018.py", line 141, in __init__
    net = net.cuda()
  File "/work/sunbiao/ea-cnn-master/scripts/indi0006.py", line 143, in __init__
    net = net.cuda()
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 637, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 637, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 552, in _apply
    param_applied = fn(param)
  [Previous line repeated 1 more time]
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 637, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 552, in _apply
    param_applied = fn(param)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 637, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

During handling of the above exception, another exception occurred:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
Traceback (most recent call last):
  File "/work/sunbiao/ea-cnn-master/scripts/indi0018.py", line 230, in do_work
    m.log_record('Exception occur:%s'%(str(e)))
  File "/work/sunbiao/ea-cnn-master/scripts/indi0006.py", line 232, in do_work
    m.log_record('Exception occur:%s'%(str(e)))
UnboundLocalError: local variable 'm' referenced before assignment
UnboundLocalError: local variable 'm' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

During handling of the above exception, another exception occurred:

Exception occurs, file:indi0008, pid:30928...CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.Traceback (most recent call last):
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()

  File "/home/nature/anaconda3/envs/nas/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/work/sunbiao/ea-cnn-master/scripts/indi0018.py", line 232, in do_work
    m.log_record('Finished-Acc:%.3f'%best_acc)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/work/sunbiao/ea-cnn-master/scripts/indi0006.py", line 234, in do_work
    m.log_record('Finished-Acc:%.3f'%best_acc)
UnboundLocalError: local variable 'm' referenced before assignment
UnboundLocalError: local variable 'm' referenced before assignment
Process Process-9:
Exception occurs, file:indi0011, pid:30931...CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Process Process-12:
Traceback (most recent call last):
  File "/work/sunbiao/ea-cnn-master/scripts/indi0008.py", line 225, in do_work
    m = TrainModel()
Traceback (most recent call last):
  File "/work/sunbiao/ea-cnn-master/scripts/indi0008.py", line 143, in __init__
    net = net.cuda()
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 637, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 552, in _apply
    param_applied = fn(param)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 637, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/work/sunbiao/ea-cnn-master/scripts/indi0011.py", line 223, in do_work
    m = TrainModel()
  File "/work/sunbiao/ea-cnn-master/scripts/indi0011.py", line 141, in __init__
    net = net.cuda()
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 637, in cuda
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)

During handling of the above exception, another exception occurred:

  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
Traceback (most recent call last):
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/work/sunbiao/ea-cnn-master/scripts/indi0008.py", line 232, in do_work
    m.log_record('Exception occur:%s'%(str(e)))
  [Previous line repeated 1 more time]
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 552, in _apply
    param_applied = fn(param)
UnboundLocalError: local variable 'm' referenced before assignment
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 637, in <lambda>
    return self._apply(lambda t: t.cuda(device))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()

During handling of the above exception, another exception occurred:

  File "/home/nature/anaconda3/envs/nas/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
  File "/work/sunbiao/ea-cnn-master/scripts/indi0008.py", line 234, in do_work
    m.log_record('Finished-Acc:%.3f'%best_acc)
  File "/work/sunbiao/ea-cnn-master/scripts/indi0011.py", line 230, in do_work
    m.log_record('Exception occur:%s'%(str(e)))
UnboundLocalError: local variable 'm' referenced before assignment
UnboundLocalError: local variable 'm' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/work/sunbiao/ea-cnn-master/scripts/indi0011.py", line 232, in do_work
    m.log_record('Finished-Acc:%.3f'%best_acc)
UnboundLocalError: local variable 'm' referenced before assignment
Exception occurs, file:indi0010, pid:30930...CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Process Process-11:
Traceback (most recent call last):
  File "/work/sunbiao/ea-cnn-master/scripts/indi0010.py", line 219, in do_work
    m = TrainModel()
  File "/work/sunbiao/ea-cnn-master/scripts/indi0010.py", line 137, in __init__
    net = net.cuda()
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 637, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 552, in _apply
    param_applied = fn(param)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 637, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/work/sunbiao/ea-cnn-master/scripts/indi0010.py", line 226, in do_work
    m.log_record('Exception occur:%s'%(str(e)))
UnboundLocalError: local variable 'm' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/work/sunbiao/ea-cnn-master/scripts/indi0010.py", line 228, in do_work
    m.log_record('Finished-Acc:%.3f'%best_acc)
UnboundLocalError: local variable 'm' referenced before assignment
Exception occurs, file:indi0005, pid:30925...CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Process Process-6:
Traceback (most recent call last):
  File "/work/sunbiao/ea-cnn-master/scripts/indi0005.py", line 229, in do_work
    m = TrainModel()
  File "/work/sunbiao/ea-cnn-master/scripts/indi0005.py", line 147, in __init__
    net = net.cuda()
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 637, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 552, in _apply
    param_applied = fn(param)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 637, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/work/sunbiao/ea-cnn-master/scripts/indi0005.py", line 236, in do_work
    m.log_record('Exception occur:%s'%(str(e)))
UnboundLocalError: local variable 'm' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/work/sunbiao/ea-cnn-master/scripts/indi0005.py", line 238, in do_work
    m.log_record('Finished-Acc:%.3f'%best_acc)
UnboundLocalError: local variable 'm' referenced before assignment
Exception occurs, file:indi0002, pid:30922...CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Process Process-3:
Traceback (most recent call last):
  File "/work/sunbiao/ea-cnn-master/scripts/indi0002.py", line 223, in do_work
    m = TrainModel()
  File "/work/sunbiao/ea-cnn-master/scripts/indi0002.py", line 141, in __init__
    net = net.cuda()
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 637, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 552, in _apply
    param_applied = fn(param)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 637, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/work/sunbiao/ea-cnn-master/scripts/indi0002.py", line 230, in do_work
    m.log_record('Exception occur:%s'%(str(e)))
UnboundLocalError: local variable 'm' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/work/sunbiao/ea-cnn-master/scripts/indi0002.py", line 232, in do_work
    m.log_record('Finished-Acc:%.3f'%best_acc)
UnboundLocalError: local variable 'm' referenced before assignment
Exception occurs, file:indi0004, pid:30924...CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Process Process-5:
Traceback (most recent call last):
  File "/work/sunbiao/ea-cnn-master/scripts/indi0004.py", line 225, in do_work
    m = TrainModel()
  File "/work/sunbiao/ea-cnn-master/scripts/indi0004.py", line 143, in __init__
    net = net.cuda()
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 637, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 552, in _apply
    param_applied = fn(param)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 637, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/work/sunbiao/ea-cnn-master/scripts/indi0004.py", line 232, in do_work
    m.log_record('Exception occur:%s'%(str(e)))
UnboundLocalError: local variable 'm' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/work/sunbiao/ea-cnn-master/scripts/indi0004.py", line 234, in do_work
    m.log_record('Finished-Acc:%.3f'%best_acc)
UnboundLocalError: local variable 'm' referenced before assignment
Exception occurs, file:indi0001, pid:30921...CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Process Process-2:
Traceback (most recent call last):
  File "/work/sunbiao/ea-cnn-master/scripts/indi0001.py", line 227, in do_work
    m = TrainModel()
  File "/work/sunbiao/ea-cnn-master/scripts/indi0001.py", line 145, in __init__
    net = net.cuda()
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 637, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 552, in _apply
    param_applied = fn(param)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 637, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/work/sunbiao/ea-cnn-master/scripts/indi0001.py", line 234, in do_work
    m.log_record('Exception occur:%s'%(str(e)))
UnboundLocalError: local variable 'm' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/work/sunbiao/ea-cnn-master/scripts/indi0001.py", line 236, in do_work
    m.log_record('Finished-Acc:%.3f'%best_acc)
UnboundLocalError: local variable 'm' referenced before assignment
Traceback (most recent call last):
  File "/work/sunbiao/ea-cnn-master/scripts/indi0019.py", line 225, in do_work
    m = TrainModel()
  File "/work/sunbiao/ea-cnn-master/scripts/indi0019.py", line 143, in __init__
    net = net.cuda()
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 637, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 552, in _apply
    param_applied = fn(param)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 637, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/work/sunbiao/ea-cnn-master/scripts/indi0019.py", line 232, in do_work
    m.log_record('Exception occur:%s'%(str(e)))
UnboundLocalError: local variable 'm' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/work/sunbiao/ea-cnn-master/scripts/indi0019.py", line 234, in do_work
    m.log_record('Finished-Acc:%.3f'%best_acc)
UnboundLocalError: local variable 'm' referenced before assignment
Exception occurs, file:indi0000, pid:30920...CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Process Process-1:
Traceback (most recent call last):
  File "/work/sunbiao/ea-cnn-master/scripts/indi0000.py", line 227, in do_work
    m = TrainModel()
  File "/work/sunbiao/ea-cnn-master/scripts/indi0000.py", line 145, in __init__
    net = net.cuda()
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 637, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 552, in _apply
    param_applied = fn(param)
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 637, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/work/sunbiao/ea-cnn-master/scripts/indi0000.py", line 234, in do_work
    m.log_record('Exception occur:%s'%(str(e)))
UnboundLocalError: local variable 'm' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/home/nature/anaconda3/envs/nas/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/work/sunbiao/ea-cnn-master/scripts/indi0000.py", line 236, in do_work
    m.log_record('Finished-Acc:%.3f'%best_acc)
UnboundLocalError: local variable 'm' referenced before assignment

**Comment by 1234565556** [comment]
请问你解决了这个问题了吗？

**Comment by 1234565556** [comment]
而且我也有这个问题：UnboundLocalError: local variable 'm' referenced before assignment

**Comment by mvfo** [comment]
> 而且我也有这个问题：UnboundLocalError: local variable 'm' referenced before assignment

你好，我也出现了这个问题，请问你解决了吗？
